theme: jekyll-theme-minimal
title: Dallas It Security Guide
description: Expert IT guidance and resources for Dallas-Fort Worth businesses
google_analytics: # Add your GA tracking ID here
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
